x-oprator: &oprator
  image: nodeops/atlas-operator:testnet-eigenlayer
  restart: no
  env_file:
    - .env
  cap_drop:
    - ALL
  labels:
    - com.centurylinklabs.watchtower.enable=true
    - &autopilot com.centurylinklabs.watchtower.scope=atlaseigenlayertestnet

services:
  atlas-avs-eigenlayer-testnet-verifier:
    <<: *oprator
    container_name: atlas-avs-eigenlayer-testnet-verifier
    entrypoint: [sh, -cx]
    command:
    - |
      exec othentic-cli node attester $${AGGREGATOR_RPC} --avs-webapi http://atlas-avs-eigenlayer-testnet-operator

  atlas-avs-eigenlayer-testnet-operator:
    <<: *oprator
    entrypoint: [atlas-avs-eigenlayer-operator]
    container_name: atlas-avs-eigenlayer-testnet-operator

  atlas-avs-eigenlayer-testnet-autopilot:
    image: containrrr/watchtower:1.7.1
    container_name: atlas-avs-eigenlayer-testnet-autopilot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 3600
      WATCHTOWER_LABEL_ENABLE: true
      ## Can enable notifications as well for the updates for more https://containrrr.dev/shoutrrr/v0.8/services/overview/#services_overview
      # WATCHTOWER_NOTIFICATION_URL: "discord://token@channel slack://watchtower@token-a/token-b/token-c"
      # WATCHTOWER_NOTIFICATION_TEMPLATE: "{{range .}}{{.Time.Format \"2006-01-02 15:04:05\"}} ({{.Level}}): {{.Message}}{{println}}{{end}}"
    labels:
      - *autopilot
